// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/18/2025, 1:28:53 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/nhatnt1/Projects/shop_fe/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nhatnt1/Projects/shop_fe/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nhatnt1/Projects/shop_fe/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nhatnt1/Projects/shop_fe/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nhatnt1/Projects/shop_fe/plugins/**/*.{js,ts,mjs}","/Users/nhatnt1/Projects/shop_fe/composables/**/*.{js,ts,mjs}","/Users/nhatnt1/Projects/shop_fe/utils/**/*.{js,ts,mjs}","/Users/nhatnt1/Projects/shop_fe/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nhatnt1/Projects/shop_fe/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/nhatnt1/Projects/shop_fe/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/nhatnt1/Projects/shop_fe/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;